routes:
  /membership/: members/membership
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /blog/:
    controller: channel
    template: blog
    filter: tag:-home
  /shop/online-class/: shop/online-class
  /shop/webinar/: shop/webinar
  /shop/digital-book/: shop/digital-book
  /shop/etc/: shop/etc
  /shop/my-purchases/: shop/my-purchases

collections:
  /:
    permalink: /{slug}/
    template: home

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/